package imgsearch.gui;

import ImgSearch.Constants;
import ImgSearch.clustering.Cluster;
import ImgSearch.clustering.KMeans;
import ImgSearch.util.FindTextFiles;
import imgsearch.indexing.ClusterReader;
import imgsearch.indexing.ClusterWriter;
import imgsearch.search.ImageResult;
import imgsearch.search.ImageSearcher;
import imgsearch.indexing.Index;
import imgsearch.indexing.IndexReader;
import imgsearch.indexing.IndexWriter;
import imgsearch.util.GraphicsUtilities;
import imgsearch.util.ImageFileFilter;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.SwingWorker;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
//import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author abc
 * @author denny
 */
public class MainFrame extends javax.swing.JFrame {

    private JFileChooser folderChooser = new JFileChooser();
    private JFileChooser imageChooser = new JFileChooser();
    private SwingWorker<List<ImageResult>, ImageResult> searchWorker;
    private SwingWorker<String, Void> indexWorker;
    private SwingWorker<String, Void> browseWorker;
    private long time;
    private int numIndex;

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        try {
            inititalizeIndexBrowser();
        } catch (IOException ex) {
            browsePanel.setVisible(false);

        }
    }

    private void inititalizeIndexBrowser() throws IOException {
        IndexReader indexReader = new IndexReader();
        indexReader.open();
        int clustSize = indexReader.numCluster();
        indexReader.close();
        if (clustSize < 2) {
            browsePanel.setVisible(false);
            return;
        }


        //enabled clustId combobox
        Integer[] nums = new Integer[clustSize];
        for (int i = 0; i < clustSize; i++) {
            nums[i] = i + 1;
        }

        thumbIndexPanel.getListModel().clear();
        clustIdComboBox.setModel(new DefaultComboBoxModel(nums));
        browsePanel.setVisible(true);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        cbirTab = new javax.swing.JTabbedPane();
        searchTab = new javax.swing.JPanel();
        queryPanel = new javax.swing.JPanel();
        imagePathText = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        LogoSmallLabel = new javax.swing.JLabel();
        imagePanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        betaLabel1 = new javax.swing.JLabel();
        betaText = new javax.swing.JTextField();
        alphaLabel1 = new javax.swing.JLabel();
        alphaText = new javax.swing.JTextField();
        useClusterCheck = new javax.swing.JCheckBox();
        resultPanel = new javax.swing.JPanel();
        searchProgress = new javax.swing.JProgressBar();
        statusLabel = new javax.swing.JLabel();
        thumbnailPanel = new imgsearch.gui.JThumbnailPanel();
        indexingTab = new javax.swing.JPanel();
        folderPanel = new javax.swing.JPanel();
        folderText = new javax.swing.JTextField();
        browseFolderButton = new javax.swing.JButton();
        startIndexButton = new javax.swing.JButton();
        numClusterLabel = new javax.swing.JLabel();
        numClusterCombo = new javax.swing.JComboBox();
        maxIterLabel = new javax.swing.JLabel();
        maxIterText = new javax.swing.JTextField();
        progressPanel = new javax.swing.JPanel();
        indexProgress = new javax.swing.JProgressBar();
        indexingStatusLabel = new javax.swing.JLabel();
        browsePanel = new javax.swing.JPanel();
        browseIndexProgress = new javax.swing.JProgressBar();
        browseIndexLabel = new javax.swing.JLabel();
        thumbIndexPanel = new imgsearch.gui.JThumbnailPanel();
        selectClusterLabel = new javax.swing.JLabel();
        clustIdComboBox = new javax.swing.JComboBox();
        viewDataButton = new javax.swing.JButton();
        aboutTab = new javax.swing.JPanel();
        creditsPanel = new javax.swing.JPanel();
        descLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        folderText1 = new javax.swing.JTextField();
        browseFolderButton1 = new javax.swing.JButton();
        txtType = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jLabel5.setText("Similarity Treshold :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Image and Text Serach Engine");

        queryPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Images"));

        imagePathText.setEditable(false);

        browseButton.setText("Browse ...");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(255, 204, 204));
        searchButton.setFont(new java.awt.Font("Tahoma", 0, 18));
        searchButton.setForeground(new java.awt.Color(102, 102, 102));
        searchButton.setText("Search");
        searchButton.setEnabled(false);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        LogoSmallLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image1.jpg"))); // NOI18N

        imagePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        imagePanel.setPreferredSize(new java.awt.Dimension(128, 28));
        imagePanel.setLayout(new java.awt.BorderLayout());
        imagePanel.add(imageLabel, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        betaLabel1.setText("Rough filtering const");

        betaText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        betaText.setText("0.2");
        betaText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                betaTextCaretUpdate(evt);
            }
        });

        alphaLabel1.setText("Precise Filtering Threshold");

        alphaText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        alphaText.setText("0.3");
        alphaText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                alphaTextCaretUpdate(evt);
            }
        });

        useClusterCheck.setSelected(true);
        useClusterCheck.setText("K-Means");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(betaLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(betaText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alphaLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alphaText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(useClusterCheck))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(betaLabel1)
                .addComponent(betaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(alphaLabel1)
                .addComponent(alphaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(useClusterCheck))
        );

        javax.swing.GroupLayout queryPanelLayout = new javax.swing.GroupLayout(queryPanel);
        queryPanel.setLayout(queryPanelLayout);
        queryPanelLayout.setHorizontalGroup(
            queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(queryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(queryPanelLayout.createSequentialGroup()
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, queryPanelLayout.createSequentialGroup()
                        .addComponent(imagePathText, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(browseButton))
                    .addComponent(LogoSmallLabel))
                .addContainerGap())
        );
        queryPanelLayout.setVerticalGroup(
            queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(queryPanelLayout.createSequentialGroup()
                .addComponent(LogoSmallLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imagePathText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        resultPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Result"));

        statusLabel.setText("Done ...");

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(thumbnailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultPanelLayout.createSequentialGroup()
                        .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)))
                .addContainerGap())
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(thumbnailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusLabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout searchTabLayout = new javax.swing.GroupLayout(searchTab);
        searchTab.setLayout(searchTabLayout);
        searchTabLayout.setHorizontalGroup(
            searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(queryPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        searchTabLayout.setVerticalGroup(
            searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(queryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        cbirTab.addTab("Search", searchTab);

        folderPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Indexing Path"));

        folderText.setEditable(false);

        browseFolderButton.setText("Browse ...");
        browseFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseFolderButtonActionPerformed(evt);
            }
        });

        startIndexButton.setText("Start Indexing");
        startIndexButton.setEnabled(false);
        startIndexButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startIndexButtonActionPerformed(evt);
            }
        });

        numClusterLabel.setText("Number of Clusters : ");

        numClusterCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1" }));
        numClusterCombo.setEnabled(false);

        maxIterLabel.setText("Maximum Iteration :");

        maxIterText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        maxIterText.setText("200");
        maxIterText.setEnabled(false);
        maxIterText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                maxIterTextCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout folderPanelLayout = new javax.swing.GroupLayout(folderPanel);
        folderPanel.setLayout(folderPanelLayout);
        folderPanelLayout.setHorizontalGroup(
            folderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(folderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(folderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(folderPanelLayout.createSequentialGroup()
                        .addComponent(folderText, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseFolderButton))
                    .addGroup(folderPanelLayout.createSequentialGroup()
                        .addComponent(startIndexButton)
                        .addGap(18, 18, 18)
                        .addComponent(numClusterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numClusterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(maxIterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxIterText, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        folderPanelLayout.setVerticalGroup(
            folderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(folderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(folderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(folderText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseFolderButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(folderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startIndexButton)
                    .addComponent(numClusterLabel)
                    .addComponent(numClusterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxIterLabel)
                    .addComponent(maxIterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        progressPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Indexing Progress"));

        javax.swing.GroupLayout progressPanelLayout = new javax.swing.GroupLayout(progressPanel);
        progressPanel.setLayout(progressPanelLayout);
        progressPanelLayout.setHorizontalGroup(
            progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(progressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(indexingStatusLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
                    .addComponent(indexProgress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE))
                .addContainerGap())
        );
        progressPanelLayout.setVerticalGroup(
            progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(progressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(indexProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(indexingStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
        );

        browsePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Browse Indexs"));

        browseIndexLabel.setText("Done ...");

        selectClusterLabel.setText("Select Cluster : ");

        clustIdComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));

        viewDataButton.setText("View Data");
        viewDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDataButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout browsePanelLayout = new javax.swing.GroupLayout(browsePanel);
        browsePanel.setLayout(browsePanelLayout);
        browsePanelLayout.setHorizontalGroup(
            browsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, browsePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(browsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(thumbIndexPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
                    .addGroup(browsePanelLayout.createSequentialGroup()
                        .addComponent(browseIndexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseIndexProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, browsePanelLayout.createSequentialGroup()
                        .addComponent(selectClusterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clustIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewDataButton)))
                .addContainerGap())
        );
        browsePanelLayout.setVerticalGroup(
            browsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, browsePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(browsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectClusterLabel)
                    .addComponent(clustIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewDataButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(thumbIndexPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addGroup(browsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(browseIndexProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseIndexLabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout indexingTabLayout = new javax.swing.GroupLayout(indexingTab);
        indexingTab.setLayout(indexingTabLayout);
        indexingTabLayout.setHorizontalGroup(
            indexingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, indexingTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(indexingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(browsePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(folderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progressPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        indexingTabLayout.setVerticalGroup(
            indexingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indexingTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(folderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(browsePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        cbirTab.addTab("Indexing", indexingTab);

        creditsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        descLabel.setFont(new java.awt.Font("Tahoma", 0, 18));
        descLabel.setText("Text Based Search");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "File Name", "Type", "Size", "Create Time", "Modify Time", "Location"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnSearch.setText("Search ");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtSearch.setText("Enter file name");

        jLabel2.setText("Enter file name");

        jLabel1.setText("Select Location:");

        folderText1.setEditable(false);

        browseFolderButton1.setText("Browse ...");
        browseFolderButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseFolderButton1ActionPerformed(evt);
            }
        });

        txtType.setText(".txt");

        jLabel3.setText("File Extension");

        javax.swing.GroupLayout creditsPanelLayout = new javax.swing.GroupLayout(creditsPanel);
        creditsPanel.setLayout(creditsPanelLayout);
        creditsPanelLayout.setHorizontalGroup(
            creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditsPanelLayout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(descLabel)
                .addContainerGap(396, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creditsPanelLayout.createSequentialGroup()
                .addContainerGap(412, Short.MAX_VALUE)
                .addGroup(creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseFolderButton1))
                .addGap(75, 75, 75)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creditsPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(creditsPanelLayout.createSequentialGroup()
                            .addGap(84, 84, 84)
                            .addGroup(creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(creditsPanelLayout.createSequentialGroup()
                                    .addComponent(folderText1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                    .addGap(380, 380, 380))
                                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        creditsPanelLayout.setVerticalGroup(
            creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditsPanelLayout.createSequentialGroup()
                .addComponent(descLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseFolderButton1))
                .addGap(41, 41, 41)
                .addComponent(btnSearch)
                .addContainerGap(487, Short.MAX_VALUE))
            .addGroup(creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(creditsPanelLayout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addGroup(creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(folderText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(11, 11, 11)
                    .addGroup(creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(47, 47, 47)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(35, Short.MAX_VALUE)))
        );

        creditsPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {browseFolderButton1, folderText1});

        javax.swing.GroupLayout aboutTabLayout = new javax.swing.GroupLayout(aboutTab);
        aboutTab.setLayout(aboutTabLayout);
        aboutTabLayout.setHorizontalGroup(
            aboutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(creditsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        aboutTabLayout.setVerticalGroup(
            aboutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(creditsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        cbirTab.addTab("Text Search", aboutTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbirTab, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbirTab, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseFolderButtonActionPerformed
        folderChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        folderChooser.setDialogTitle("Open Index Folder ...");
        folderChooser.showDialog(this, "Open");
        File f = folderChooser.getSelectedFile();
        if (f == null) {
            startIndexButton.setEnabled(false);
            numClusterCombo.setEnabled(false);
            maxIterText.setEnabled(false);
            return;
        }
        folderText.setText(f.getAbsolutePath());
        startIndexButton.setEnabled(true);


        File[] files = f.listFiles(new ImageFileFilter(false));
        if (files.length == 0) {
            return;
        }

        //enabled numCluster combobox
        int numOpt = files.length; 
        Integer[] nums = new Integer[numOpt];
        for (int i = 0, j = 2; i < numOpt; j++, i++) {
            nums[i] = j;
        }


        numClusterCombo.setModel(new DefaultComboBoxModel(nums));
        numClusterCombo.setEnabled(true);
        maxIterText.setEnabled(true);


    }//GEN-LAST:event_browseFolderButtonActionPerformed

    private void startIndexButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startIndexButtonActionPerformed
        indexWorker = new SwingWorker<String, Void>() {

            String notes;

            @Override
            protected String doInBackground() throws Exception {
                File folder = folderChooser.getSelectedFile();
                // image filter masih nge-bug
                File[] files = folder.listFiles(new ImageFileFilter(false));
                //System.out.println(files.length);
                if (!folder.isDirectory() || folder == null || files.length == 0) {
                    notes = "FAIL";
                    return notes;
                }

                startIndexButton.setEnabled(false);
                viewDataButton.setEnabled(false);
                indexProgress.setStringPainted(true);
                time = System.currentTimeMillis();
                IndexWriter indexWriter = new IndexWriter();
                List<Index> indexes = new ArrayList<Index>();
                // feature extraction
                numIndex = 1;
                for (File f : files) {
                    //Resize every image to 256 x 256
                    try {
                        BufferedImage bufferedImage = ImageIO.read(f);
                        if (bufferedImage.getHeight(null) != Constants.IMAGE_HEIGHT
                                || bufferedImage.getWidth(null) != Constants.IMAGE_WIDTH) {
                            bufferedImage = GraphicsUtilities.resizeImage(bufferedImage,
                                    Constants.IMAGE_WIDTH, Constants.IMAGE_HEIGHT);
                        }
                        indexingStatusLabel.setText("Extracting image : " + f.getAbsolutePath());
                        Index index = indexWriter.getIndex(bufferedImage);
                        
                        //Set progress according to files length
                        indexProgress.setValue(numIndex * 100 / files.length);
                        index.setFilePath(f.getAbsolutePath());
                        //indexWriter.addIndex(index);
                        indexes.add(index);
                        numIndex++;
                    } catch (IOException ex) {
                        ex.printStackTrace();
                    }
                }

                // k-means clustering
                KMeans kMeans = new KMeans();
                //get text from max iteration feild
                int maxIter = Integer.parseInt(maxIterText.getText());
                kMeans.setNumCluster(Integer.parseInt(numClusterCombo.getSelectedItem().toString()));
                kMeans.setMaxIteration(maxIter);
                indexingStatusLabel.setText("Clustering Indexs ....");
                indexProgress.setIndeterminate(true);
                //Compute Clusters
                kMeans.computeCluster(indexWriter, indexes);
                indexProgress.setIndeterminate(false);

                indexingStatusLabel.setText("Saving Indexs ....");
                // indexing ...
                Cluster[] clusters = kMeans.getClusters();
                // create root index
                indexWriter.open();
                for (Cluster c : clusters) {
                    indexWriter.addCluster(c);
                }
                indexWriter.close();

//================================================================================================================
//After adding centroid to document
//create clusters index
                numIndex = 1;
                ClusterWriter clusterWriter = new ClusterWriter();
                for (int idx = 0; idx < kMeans.getNumCluster(); idx++) {
                    //System.out.println(kMeans.getNumCluster());
                    clusterWriter.open(idx);
                    for (Index ix : clusters[idx].getMembers()) {
                        System.out.println("AAY");
                        //System.out.println("AA");
                        indexingStatusLabel.setText("Add image " + ix.getFilePath() + " to cluster-" + idx);
                        clusterWriter.addIndex(ix);
                        indexProgress.setValue(numIndex * 100 / files.length);
                        numIndex++;
                    }
                    clusterWriter.close();
                }

                notes = "SUCCESS";
                return notes;
            }

            @Override
            protected void done() {
                indexProgress.setValue(0);
                if ("FAIL".equals(notes)) {
                    indexingStatusLabel.setText("Can't Index images because path has no images");
                    browsePanel.setVisible(false);
                    return;
                }
                indexingStatusLabel.setText("Finished indexing " + (numIndex - 1) + " images in " + ((System.currentTimeMillis() - time) / 1000) + " s.");
                //enabled clustId combobox
                Integer clustSize = (Integer) numClusterCombo.getSelectedItem();
                Integer[] nums = new Integer[clustSize];
                for (int i = 0; i < clustSize; i++) {
                    nums[i] = i + 1;
                }

                thumbIndexPanel.getListModel().clear();
                clustIdComboBox.setModel(new DefaultComboBoxModel(nums));
                browsePanel.setVisible(true);
                //thumbIndexPanel.setVisible(false);
                startIndexButton.setEnabled(true);
                viewDataButton.setEnabled(true);
            }
        };

        indexWorker.execute();
        /**
        // TODO add your handling code here:
        ImageIndexer indexer = new ImageIndexer();
        startIndexButton.setEnabled(false);
        try {
        indexer.indexToDatabase(folderChooser.getSelectedFile(), !addCheck.isSelected());
        } catch (Exception e) {
        }
        startIndexButton.setEnabled(true);*/
    }//GEN-LAST:event_startIndexButtonActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        try {
            imageChooser.setFileFilter(new ImageFileFilter());
            imageChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            imageChooser.setDialogTitle("Open Query Image ...");
            imageChooser.showDialog(this, "Open");
            File f = imageChooser.getSelectedFile();
            if (f == null) {
                return;
            }
            imagePathText.setText(f.getAbsolutePath());
            BufferedImage bufferedImage = ImageIO.read(imageChooser.getSelectedFile());
            bufferedImage = GraphicsUtilities.resizeImage(bufferedImage, 125, 140);
            imageLabel.setIcon(new ImageIcon(bufferedImage));

        } catch (IOException ex) {
            ex.printStackTrace();
        }
        checkInputSearch();

    }//GEN-LAST:event_browseButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // check
        searchWorker = new SwingWorker<List<ImageResult>, ImageResult>() {

            @Override
            protected List<ImageResult> doInBackground() throws Exception {
                thumbnailPanel.setEnabled(false);
                ImageSearcher searcher = new ImageSearcher();
                BufferedImage bufferedImage = ImageIO.read(imageChooser.getSelectedFile());
                if (bufferedImage.getHeight(null) != Constants.IMAGE_HEIGHT
                        || bufferedImage.getWidth(null) != Constants.IMAGE_WIDTH) {
                    bufferedImage = GraphicsUtilities.resizeImage(bufferedImage,
                            Constants.IMAGE_WIDTH, Constants.IMAGE_HEIGHT);
                }
                time = System.currentTimeMillis();
                searchProgress.setIndeterminate(true);
                statusLabel.setText("Search Images ...");
                List<ImageResult> r = searcher.search(bufferedImage, Double.parseDouble(alphaText.getText()),
                        Double.parseDouble(betaText.getText()), useClusterCheck.isSelected());
                //System.out.println(r.size());
                return r;
            }

            @Override
            protected void done() {
                try {
                    thumbnailPanel.getListModel().clear();
                    List<ImageResult> r = get();
                    searchProgress.setIndeterminate(false);


                    if (r.isEmpty()) {
                        thumbnailPanel.changePageButtonState();
                        statusLabel.setText("No images found ...");
                    } else {
                        thumbnailPanel.getListModel().setPageOffset(0);
                        thumbnailPanel.getListModel().add(r);
                        thumbnailPanel.changePageButtonState();
                        statusLabel.setText("Finished in " + ((double) (System.currentTimeMillis() - time) / 1000) + " s.");
                    }



                } catch (Exception e) {
                    e.printStackTrace();
                    searchProgress.setIndeterminate(false);
                    statusLabel.setText("Can't search images. Please do indexing ...");
                } finally {
                    thumbnailPanel.setEnabled(true);
                }
            }
        };


        searchWorker.execute();
        /**
        try {
        ImageSearcher searcher = new ImageSearcher();
        BufferedImage bufferedImage = ImageIO.read(imageChooser.getSelectedFile());
        if (bufferedImage.getHeight(null) != Constants.IMAGE_HEIGHT
        || bufferedImage.getWidth(null) != Constants.IMAGE_WIDTH) {
        bufferedImage = GraphicsUtilities.createCompatibleImage(bufferedImage,
        Constants.IMAGE_WIDTH, Constants.IMAGE_HEIGHT);
        }
        List<ImageResult> r = searcher.search(bufferedImage, 0.3, 0.5);
        thumbnailPanel.getListModel().clear();
        thumbnailPanel.getListModel().add(r);
        thumbnailPanel.changePageButtonState();
        } catch (IOException ex) {
        }*/
    }//GEN-LAST:event_searchButtonActionPerformed

    private void betaTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_betaTextCaretUpdate

        checkInputSearch();
    }//GEN-LAST:event_betaTextCaretUpdate

    private void alphaTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_alphaTextCaretUpdate
        checkInputSearch();
    }//GEN-LAST:event_alphaTextCaretUpdate

    private void maxIterTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_maxIterTextCaretUpdate
        // TODO add your handling code here:
        try {
            int maxIter = Integer.parseInt(maxIterText.getText());
            if (maxIter < 1) {
                startIndexButton.setEnabled(false);
                return;
            }

        } catch (NumberFormatException nfe) {
            startIndexButton.setEnabled(false);
            return;
        }

        startIndexButton.setEnabled(true);
    }//GEN-LAST:event_maxIterTextCaretUpdate

    private void viewDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDataButtonActionPerformed
        browseWorker = new SwingWorker<String, Void>() {
            @Override
            protected String doInBackground() throws Exception {
                try {
                    thumbIndexPanel.setEnabled(false);
                    viewDataButton.setEnabled(false);
                    //thumbIndexPanel.changePageButtonState();
                    thumbIndexPanel.getListModel().setPageOffset(0);
                    thumbIndexPanel.getListModel().clear();
                    Integer clustId = (Integer) clustIdComboBox.getSelectedItem() - 1;
                    IndexReader indexReader = new IndexReader();
                    indexReader.open();
                    Cluster selectedCluster = indexReader.getCluster(clustId);
                    indexReader.close();
                    if (selectedCluster == null) {
                        return "";

                    }
                    ClusterReader clusterReader = new ClusterReader();
                    clusterReader.open(clustId);
                    List<Index> indexs = clusterReader.getIndexes();
                    int dataSize = indexs.size();
                    clusterReader.close();
                    int i = 1;
                    browseIndexLabel.setText("Viewing Data in cluster-" + clustId + " ...");
                    browseIndexProgress.setValue(0);
                    for (Index index : indexs) {
                        ImageResult imageResult = new ImageResult();
                        imageResult.setPath(index.getFilePath());
                        imageResult.setSimilarity(selectedCluster.getDistance(index));
                        try {
                            BufferedImage bufferedImage = ImageIO.read(new File(index.getFilePath()));
                            imageResult.setBufferedImage(GraphicsUtilities.resizeImage(bufferedImage,
                                    Constants.THUMB_WIDTH, Constants.THUMB_HEIGHT));
                            thumbIndexPanel.getListModel().add(imageResult);
                            browseIndexProgress.setValue(i * 100 / dataSize);
                        } catch (IOException ex) {
                        }
                        i++;
                    }
                    thumbIndexPanel.changePageButtonState();

                } catch (IOException ex) {
                    ex.printStackTrace();
                }

                return "";
            }

            @Override
            protected void done() {
                browseIndexLabel.setText("Done.");
                thumbIndexPanel.setEnabled(true);
                viewDataButton.setEnabled(true);
            }
        };

        browseWorker.execute();

    }//GEN-LAST:event_viewDataButtonActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
if("".equalsIgnoreCase(folderText1.getText()))return;
if("".equalsIgnoreCase(txtType.getText()))return;

    FindTextFiles l=new FindTextFiles();
  List f=  l.search(folderText1.getText(),txtType.getText());
Iterator itr = f.iterator();
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
 Vector row=null;
        while(itr.hasNext())
        {
            System.out.println(itr.next());
             row = new Vector();
    row.add(itr.next());

    model.addRow(row);
        }




    }//GEN-LAST:event_btnSearchActionPerformed

    private void browseFolderButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseFolderButton1ActionPerformed
        folderChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        folderChooser.setDialogTitle("Open Index Folder ...");
        folderChooser.showDialog(this, "Open");
        File f = folderChooser.getSelectedFile();

        folderText1.setText(f.getAbsolutePath());



        File[] files = f.listFiles(new ImageFileFilter(false));
        if (files.length == 0) {
            return;
        }

        //enabled numCluster combobox
        int numOpt = (files.length / 2) - 1;
        Integer[] nums = new Integer[numOpt];
        for (int i = 0, j = 2; i < numOpt; j++, i++) {
            nums[i] = j;
        }

    }//GEN-LAST:event_browseFolderButton1ActionPerformed

    private void checkInputSearch() {
        if (imageChooser.getSelectedFile() == null) {
            searchButton.setEnabled(false);
            return;
        }

        try {
            double a = Double.parseDouble(alphaText.getText());
            double b = Double.parseDouble(betaText.getText());
            if (a > 1 || a < 0 || b > 1 || b < 0) {
                searchButton.setEnabled(false);
                return;
            }

        } catch (NumberFormatException nfe) {
            searchButton.setEnabled(false);
            return;
        }

        searchButton.setEnabled(true);
    }

   
     public static void main(String args[]) {

       /*   JFrame.setDefaultLookAndFeelDecorated(true);
		SubstanceLookAndFeel
				.setCurrentTheme("org.jvnet.substance.theme.SubstanceRaspberryTheme");
		SubstanceLookAndFeel
				.setCurrentButtonShaper("org.jvnet.substance.button.StandardButtonShaper");
		SubstanceLookAndFeel
				.setCurrentWatermark("org.jvnet.substance.watermark.SubstanceBubblesWatermark");
		SubstanceLookAndFeel
				.setCurrentGradientPainter("SpecularGradientPainter");
		try {
			UIManager.setLookAndFeel(new SubstanceLookAndFeel());
		} catch (UnsupportedLookAndFeelException e) {

			e.printStackTrace();
		}*/
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrame().setVisible(true);
			}
		});
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoSmallLabel;
    private javax.swing.JPanel aboutTab;
    private javax.swing.JLabel alphaLabel1;
    private javax.swing.JTextField alphaText;
    private javax.swing.JLabel betaLabel1;
    private javax.swing.JTextField betaText;
    private javax.swing.JButton browseButton;
    private javax.swing.JButton browseFolderButton;
    private javax.swing.JButton browseFolderButton1;
    private javax.swing.JLabel browseIndexLabel;
    private javax.swing.JProgressBar browseIndexProgress;
    private javax.swing.JPanel browsePanel;
    private javax.swing.JButton btnSearch;
    private javax.swing.JTabbedPane cbirTab;
    private javax.swing.JComboBox clustIdComboBox;
    private javax.swing.JPanel creditsPanel;
    private javax.swing.JLabel descLabel;
    private javax.swing.JPanel folderPanel;
    private javax.swing.JTextField folderText;
    private javax.swing.JTextField folderText1;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JTextField imagePathText;
    private javax.swing.JProgressBar indexProgress;
    private javax.swing.JLabel indexingStatusLabel;
    private javax.swing.JPanel indexingTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel maxIterLabel;
    private javax.swing.JTextField maxIterText;
    private javax.swing.JComboBox numClusterCombo;
    private javax.swing.JLabel numClusterLabel;
    private javax.swing.JPanel progressPanel;
    private javax.swing.JPanel queryPanel;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JProgressBar searchProgress;
    private javax.swing.JPanel searchTab;
    private javax.swing.JLabel selectClusterLabel;
    private javax.swing.JButton startIndexButton;
    private javax.swing.JLabel statusLabel;
    private imgsearch.gui.JThumbnailPanel thumbIndexPanel;
    private imgsearch.gui.JThumbnailPanel thumbnailPanel;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtType;
    private javax.swing.JCheckBox useClusterCheck;
    private javax.swing.JButton viewDataButton;
    // End of variables declaration//GEN-END:variables
}
